-- Songs table:
insert into songs (Title, Artist, genre) values ('Smells Like Teen Spirit', 'Radiohead', 'punk');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Drake', 'electronic');
insert into songs (Title, Artist, genre) values ('Imagine', 'Queen', 'pop');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Metallica', 'punk');
insert into songs (Title, Artist, genre) values ('Wonderwall', 'Queen', 'metal');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Metallica', 'metal');
insert into songs (Title, Artist, genre) values ('Thriller', 'Lil Wayne', 'latin');
insert into songs (Title, Artist, genre) values ('Like a Rolling Stone', 'Outkast', 'pop');
insert into songs (Title, Artist, genre) values ('Hey Jude', 'Kendrick Lamar', 'country');
insert into songs (Title, Artist, genre) values ('Stairway to Heaven', 'The Rolling Stones', 'country');
insert into songs (Title, Artist, genre) values ('Thriller', 'Pink Floyd', 'rap');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Drake', 'country');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Travis Scott', 'reggae');
insert into songs (Title, Artist, genre) values ('Imagine', 'Kanye West', 'alternative');
insert into songs (Title, Artist, genre) values ('Like a Rolling Stone', 'Jay-Z', 'rap');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Coldplay', 'rock');
insert into songs (Title, Artist, genre) values ('Hey Jude', 'Kendrick Lamar', 'jazz');
insert into songs (Title, Artist, genre) values ('Imagine', 'Outkast', 'blues');
insert into songs (Title, Artist, genre) values ('Like a Rolling Stone', 'Drake', 'rap');
insert into songs (Title, Artist, genre) values ('Hotel California', 'Queen', 'hip hop');
insert into songs (Title, Artist, genre) values ('Bohemian Rhapsody', 'Lil Wayne', 'blues');
insert into songs (Title, Artist, genre) values ('Wonderwall', 'AC/DC', 'classical');
insert into songs (Title, Artist, genre) values ('Thriller', 'Led Zeppelin', 'latin');
insert into songs (Title, Artist, genre) values ('Hotel California', 'Kendrick Lamar', 'country');
insert into songs (Title, Artist, genre) values ('Hey Jude', 'Snoop Dogg', 'rap');
insert into songs (Title, Artist, genre) values ('Smells Like Teen Spirit', 'Jay-Z', 'jazz');
insert into songs (Title, Artist, genre) values ('Thriller', 'Radiohead', 'hip hop');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Kendrick Lamar', 'punk');
insert into songs (Title, Artist, genre) values ('Thriller', 'Eminem', 'soul');
insert into songs (Title, Artist, genre) values ('Thriller', 'Drake', 'pop');
insert into songs (Title, Artist, genre) values ('Like a Rolling Stone', 'Radiohead', 'rap');
insert into songs (Title, Artist, genre) values ('Hey Jude', 'Kanye West', 'folk');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Drake', 'electronic');
insert into songs (Title, Artist, genre) values ('Wonderwall', 'The Rolling Stones', 'latin');
insert into songs (Title, Artist, genre) values ('Stairway to Heaven', 'Led Zeppelin', 'folk');
insert into songs (Title, Artist, genre) values ('Hey Jude', 'AC/DC', 'electronic');
insert into songs (Title, Artist, genre) values ('Hey Jude', 'Led Zeppelin', 'hip hop');
insert into songs (Title, Artist, genre) values ('Sweet Child o'' Mine', 'Led Zeppelin', 'blues');
insert into songs (Title, Artist, genre) values ('Smells Like Teen Spirit', 'Travis Scott', 'r&b');
insert into songs (Title, Artist, genre) values ('Wonderwall', 'Outkast', 'folk');
insert into songs (Title, Artist, genre) values ('Imagine', 'Kanye West', 'soul');
insert into songs (Title, Artist, genre) values ('Stairway to Heaven', 'Jay-Z', 'metal');
insert into songs (Title, Artist, genre) values ('Stairway to Heaven', 'Pink Floyd', 'alternative');
insert into songs (Title, Artist, genre) values ('Bohemian Rhapsody', 'Led Zeppelin', 'folk');
insert into songs (Title, Artist, genre) values ('Stairway to Heaven', 'Outkast', 'reggae');
insert into songs (Title, Artist, genre) values ('Imagine', 'Nirvana', 'blues');
insert into songs (Title, Artist, genre) values ('Smells Like Teen Spirit', 'Radiohead', 'electronic');
insert into songs (Title, Artist, genre) values ('Stairway to Heaven', 'Pink Floyd', 'dance');
insert into songs (Title, Artist, genre) values ('Smells Like Teen Spirit', 'The Rolling Stones', 'classical');
insert into songs (Title, Artist, genre) values ('Stairway to Heaven', 'Radiohead', 'rock');

-- Members table:
insert into members (Firstname, Lastname, Email) values ('Kristi', 'Batalle', 'kbatalle0@bizjournals.com');
insert into members (Firstname, Lastname, Email) values ('Aurelea', 'Caple', 'acaple1@blogspot.com');
insert into members (Firstname, Lastname, Email) values ('Stacia', 'Yaakov', 'syaakov2@nydailynews.com');
insert into members (Firstname, Lastname, Email) values ('Waylan', 'Ethelstone', 'wethelstone3@webnode.com');
insert into members (Firstname, Lastname, Email) values ('Bogey', 'Gidney', 'bgidney4@amazonaws.com');
insert into members (Firstname, Lastname, Email) values ('Bridgette', 'Cappineer', 'bcappineer5@smugmug.com');
insert into members (Firstname, Lastname, Email) values ('Jermayne', 'Abby', 'jabby6@hhs.gov');
insert into members (Firstname, Lastname, Email) values ('Milzie', 'Chalcraft', 'mchalcraft7@engadget.com');
insert into members (Firstname, Lastname, Email) values ('Aliza', 'Weddell', 'aweddell8@bloomberg.com');
insert into members (Firstname, Lastname, Email) values ('Terri', 'Dulany', 'tdulany9@example.com');
insert into members (Firstname, Lastname, Email) values ('Gregorius', 'Ainley', 'gainleya@wired.com');
insert into members (Firstname, Lastname, Email) values ('Celestine', 'McDuff', 'cmcduffb@ocn.ne.jp');
insert into members (Firstname, Lastname, Email) values ('Revkah', 'Danielsohn', 'rdanielsohnc@irs.gov');
insert into members (Firstname, Lastname, Email) values ('Raphaela', 'Stave', 'rstaved@springer.com');
insert into members (Firstname, Lastname, Email) values ('Clyde', 'Timoney', 'ctimoneye@barnesandnoble.com');
insert into members (Firstname, Lastname, Email) values ('Gabi', 'Wolstencroft', 'gwolstencroftf@yale.edu');
insert into members (Firstname, Lastname, Email) values ('Rica', 'Roscamps', 'rroscampsg@devhub.com');
insert into members (Firstname, Lastname, Email) values ('Dareen', 'Colquite', 'dcolquiteh@cocolog-nifty.com');
insert into members (Firstname, Lastname, Email) values ('Bevon', 'Renner', 'brenneri@123-reg.co.uk');
insert into members (Firstname, Lastname, Email) values ('Lefty', 'Mowsdill', 'lmowsdillj@github.io');
insert into members (Firstname, Lastname, Email) values ('Meghann', 'Lenchenko', 'mlenchenkok@cnn.com');
insert into members (Firstname, Lastname, Email) values ('Olimpia', 'Curryer', 'ocurryerl@techcrunch.com');
insert into members (Firstname, Lastname, Email) values ('Jacob', 'Spreull', 'jspreullm@gizmodo.com');
insert into members (Firstname, Lastname, Email) values ('Karita', 'Bewicke', 'kbewicken@typepad.com');
insert into members (Firstname, Lastname, Email) values ('Jereme', 'Somerled', 'jsomerledo@yellowpages.com');
insert into members (Firstname, Lastname, Email) values ('Obadiah', 'Le land', 'olelandp@hexun.com');
insert into members (Firstname, Lastname, Email) values ('Glyn', 'Custance', 'gcustanceq@instagram.com');
insert into members (Firstname, Lastname, Email) values ('Gladi', 'Babber', 'gbabberr@ca.gov');
insert into members (Firstname, Lastname, Email) values ('Fiorenze', 'Isacoff', 'fisacoffs@jiathis.com');
insert into members (Firstname, Lastname, Email) values ('Colly', 'Jacquet', 'cjacquett@over-blog.com');
insert into members (Firstname, Lastname, Email) values ('Helena', 'Arstall', 'harstallu@weather.com');
insert into members (Firstname, Lastname, Email) values ('Orelie', 'Kitchingman', 'okitchingmanv@mapquest.com');
insert into members (Firstname, Lastname, Email) values ('Ruprecht', 'Banks', 'rbanksw@skyrock.com');
insert into members (Firstname, Lastname, Email) values ('Marie-ann', 'Addekin', 'maddekinx@ca.gov');
insert into members (Firstname, Lastname, Email) values ('Benedetto', 'Orkney', 'borkneyy@uiuc.edu');
insert into members (Firstname, Lastname, Email) values ('Thorndike', 'Brambley', 'tbrambleyz@dailymail.co.uk');
insert into members (Firstname, Lastname, Email) values ('Pippa', 'Totterdell', 'ptotterdell10@marketwatch.com');
insert into members (Firstname, Lastname, Email) values ('Merrile', 'Itzkowicz', 'mitzkowicz11@ning.com');
insert into members (Firstname, Lastname, Email) values ('Bliss', 'Doerrling', 'bdoerrling12@nyu.edu');
insert into members (Firstname, Lastname, Email) values ('Dory', 'Brogi', 'dbrogi13@paypal.com');
insert into members (Firstname, Lastname, Email) values ('Kimball', 'McLese', 'kmclese14@wikia.com');
insert into members (Firstname, Lastname, Email) values ('Rianon', 'Otham', 'rotham15@youku.com');
insert into members (Firstname, Lastname, Email) values ('Will', 'Pearn', 'wpearn16@constantcontact.com');
insert into members (Firstname, Lastname, Email) values ('Gannon', 'Haggard', 'ghaggard17@oracle.com');
insert into members (Firstname, Lastname, Email) values ('Prue', 'Crossgrove', 'pcrossgrove18@issuu.com');
insert into members (Firstname, Lastname, Email) values ('Kelly', 'Waplinton', 'kwaplinton19@ebay.co.uk');
insert into members (Firstname, Lastname, Email) values ('Rudy', 'Fessions', 'rfessions1a@multiply.com');
insert into members (Firstname, Lastname, Email) values ('Oswald', 'Abbison', 'oabbison1b@usda.gov');
insert into members (Firstname, Lastname, Email) values ('Hollis', 'Jarrelt', 'hjarrelt1c@chicagotribune.com');
insert into members (Firstname, Lastname, Email) values ('Abrahan', 'Farlow', 'afarlow1d@live.com');

-- Downloads
insert into downloads (SongID, MemberID, Date) values (34, 5, '2023-05-08');
insert into downloads (SongID, MemberID, Date) values (23, 27, '2020-09-19');
insert into downloads (SongID, MemberID, Date) values (12, 27, '2023-07-13');
insert into downloads (SongID, MemberID, Date) values (7, 18, '2021-09-17');
insert into downloads (SongID, MemberID, Date) values (9, 12, '2021-10-14');
insert into downloads (SongID, MemberID, Date) values (46, 42, '2018-03-06');
insert into downloads (SongID, MemberID, Date) values (29, 34, '2022-04-06');
insert into downloads (SongID, MemberID, Date) values (12, 27, '2020-12-18');
insert into downloads (SongID, MemberID, Date) values (11, 18, '2018-05-03');
insert into downloads (SongID, MemberID, Date) values (32, 2, '2022-06-21');
insert into downloads (SongID, MemberID, Date) values (38, 36, '2019-08-31');
insert into downloads (SongID, MemberID, Date) values (11, 2, '2023-09-27');
insert into downloads (SongID, MemberID, Date) values (11, 18, '2021-02-24');
insert into downloads (SongID, MemberID, Date) values (2, 12, '2023-01-04');
insert into downloads (SongID, MemberID, Date) values (32, 31, '2022-09-27');
insert into downloads (SongID, MemberID, Date) values (43, 29, '2022-07-26');
insert into downloads (SongID, MemberID, Date) values (34, 12, '2022-09-19');
insert into downloads (SongID, MemberID, Date) values (11, 21, '2022-04-13');
insert into downloads (SongID, MemberID, Date) values (34, 9, '2019-09-05');
insert into downloads (SongID, MemberID, Date) values (18, 7, '2021-08-16');
insert into downloads (SongID, MemberID, Date) values (14, 21, '2023-01-22');
insert into downloads (SongID, MemberID, Date) values (14, 39, '2019-08-10');
insert into downloads (SongID, MemberID, Date) values (27, 39, '2018-02-17');
insert into downloads (SongID, MemberID, Date) values (23, 7, '2023-03-19');
insert into downloads (SongID, MemberID, Date) values (41, 9, '2019-11-22');
insert into downloads (SongID, MemberID, Date) values (16, 45, '2022-11-21');
insert into downloads (SongID, MemberID, Date) values (27, 27, '2022-10-03');
insert into downloads (SongID, MemberID, Date) values (11, 9, '2021-04-06');
insert into downloads (SongID, MemberID, Date) values (41, 29, '2019-06-12');
insert into downloads (SongID, MemberID, Date) values (46, 4, '2022-10-21');
insert into downloads (SongID, MemberID, Date) values (2, 45, '2023-02-15');
insert into downloads (SongID, MemberID, Date) values (29, 16, '2023-08-13');
insert into downloads (SongID, MemberID, Date) values (29, 14, '2021-07-21');
insert into downloads (SongID, MemberID, Date) values (32, 39, '2018-01-18');
insert into downloads (SongID, MemberID, Date) values (14, 9, '2022-02-22');
insert into downloads (SongID, MemberID, Date) values (29, 42, '2020-05-30');
insert into downloads (SongID, MemberID, Date) values (18, 27, '2019-06-24');
insert into downloads (SongID, MemberID, Date) values (38, 47, '2021-02-25');
insert into downloads (SongID, MemberID, Date) values (32, 45, '2023-02-25');
insert into downloads (SongID, MemberID, Date) values (23, 23, '2021-03-27');
insert into downloads (SongID, MemberID, Date) values (38, 4, '2020-05-27');
insert into downloads (SongID, MemberID, Date) values (7, 27, '2020-08-01');
insert into downloads (SongID, MemberID, Date) values (20, 36, '2023-09-19');
insert into downloads (SongID, MemberID, Date) values (29, 34, '2024-01-02');
insert into downloads (SongID, MemberID, Date) values (43, 45, '2022-09-06');
insert into downloads (SongID, MemberID, Date) values (7, 12, '2020-12-08');
insert into downloads (SongID, MemberID, Date) values (32, 36, '2020-05-01');
insert into downloads (SongID, MemberID, Date) values (14, 23, '2023-10-30');
insert into downloads (SongID, MemberID, Date) values (9, 9, '2022-11-09');
insert into downloads (SongID, MemberID, Date) values (12, 16, '2022-02-18');

select * from downloads;

